using System.Text;
using System.Text.Json;
using FactorioParanoidal.FactorioMods.Execution.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FactorioParanoidal.FactorioMods.Execution.SourceGenerator {
    internal class PrototypeGenerator {
        private static readonly Dictionary<string, string> TypeMapping = new() {
            { "string", "string" },
            { "bool", "bool" },
            { "boolean", "bool" },
            { "double", "double" },
            { "float", "float" },
            { "int8", "sbyte" },
            { "uint8", "byte" },
            { "int16", "short" },
            { "uint16", "ushort" },
            { "int32", "int" },
            { "uint32", "uint" },
            { "int64", "long" },
            { "uint64", "ulong" },
            { "double_or_float", "double" },
            { "Energy", "string" },
            { "FileName", "string" },
            { "Order", "string" },
            { "Color", "object" },
            { "LocalisedString", "object" },
            { "Sound", "object" },
            { "Sprite", "object" },
            { "Animation", "object" },
            { "ItemID", "string" },
            { "EntityID", "string" },
            { "RecipeID", "string" },
            { "TechnologyID", "string" },
            { "TileID", "string" },
            { "FluidID", "string" },
            { "ItemSubGroupID", "string" },
            { "ItemGroupID", "string" },
            { "FuelCategoryID", "string" },
            { "EquipmentID", "string" },
            { "QualityID", "string" },
            { "SurfaceID", "string" },
            { "SpaceLocationID", "string" },
            { "VirtualSignalID", "string" },
        };

        private static readonly HashSet<string> Keywords = new() {
            "base", "class", "namespace", "object", "event", "delegate", "operator", "params", "checked", "unchecked",
            "default", "throw", "for", "foreach", "while", "do", "if", "else", "switch", "case", "break", "continue",
            "return",
            "using", "lock", "fixed", "new", "this", "true", "false", "null", "void", "static", "public", "private",
            "protected",
            "internal", "virtual", "override", "sealed", "abstract", "readonly", "volatile", "async", "await"
        };

        private readonly Dictionary<string, JsonElement> _allTypeDefs = new();

        private readonly HashSet<string> _generatedTypes = new();

        public void Execute(string json, SourceProductionContext context) {
            PrototypeApi? api;
            try {
                api = JsonSerializer.Deserialize<PrototypeApi>(json);
            }
            catch {
                return;
            }

            if (api == null) return;

            foreach (var t in api.Types) _allTypeDefs[t.Name] = t.Type ?? default;
            foreach (var p in api.Prototypes) _generatedTypes.Add(p.Name);
            foreach (var t in api.Types.Where(t => t.Properties != null && t.Properties.Count > 0))
                _generatedTypes.Add(t.Name);

            GeneratePrototypes(api.Prototypes, context);
            GenerateTypes(api.Types, context);
        }

        private void GeneratePrototypes(List<Prototype> prototypes, SourceProductionContext context) {
            foreach (var prototype in prototypes) {
                if (prototype.Name == "PrototypeBase") continue;

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("#pragma warning disable CS0108, CS0109");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Text.Json.Serialization;");
                sb.AppendLine();
                sb.AppendLine("namespace FactorioParanoidal.FactorioMods.Execution.Prototypes");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {prototype.Description.Replace("\n", "\n    /// ")}");
                sb.AppendLine("    /// </summary>");

                var parent = prototype.Parent ?? "PrototypeBase";
                if (parent == "FactorioPrototype" || parent == "Prototype") parent = "PrototypeBase";

                // We ALWAYS implement ILuaUserData explicitly to provide class-specific metamethods.
                // Even for abstract classes, because they might be used as base types.
                string inheritance = $" : {parent}, global::Lua.ILuaUserData";
                var abstractKeyword = prototype.Abstract ? "abstract " : "";
                sb.AppendLine($"    public {abstractKeyword}partial class {prototype.Name}{inheritance}");
                sb.AppendLine("    {");

                var properties = new List<(string LuaName, string CSharpName, string CSharpType, bool Optional)>();
                foreach (var prop in prototype.Properties) {
                    var propInfo = GenerateProperty(sb, prop, true, prototype.Name);
                    properties.Add(propInfo);
                }

                GenerateLuaBinding(sb, prototype.Name, properties, true);

                sb.AppendLine("    }");
                sb.AppendLine("}");

                context.AddSource($"Prototypes.{prototype.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        private void GenerateTypes(List<TypeDefinition> types, SourceProductionContext context) {
            foreach (var type in types.Where(t => t.Properties != null && t.Properties.Count > 0)) {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("#pragma warning disable CS0108, CS0109");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Text.Json.Serialization;");
                sb.AppendLine();
                sb.AppendLine("namespace FactorioParanoidal.FactorioMods.Execution.Prototypes");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {type.Description.Replace("\n", "\n    /// ")}");
                sb.AppendLine("    /// </summary>");

                var parent = type.Parent;
                if (parent == "FactorioPrototype" || parent == "Prototype") parent = "PrototypeBase";

                bool hasParent = !string.IsNullOrEmpty(parent);
                string inheritance =
                    hasParent ? $" : {parent}, global::Lua.ILuaUserData" : " : global::Lua.ILuaUserData";

                var abstractKeyword = type.Abstract ? "abstract " : "";
                sb.AppendLine($"    public {abstractKeyword}partial class {type.Name}{inheritance}");
                sb.AppendLine("    {");

                if (!hasParent) {
                    sb.AppendLine(
                        "        [global::System.Text.Json.Serialization.JsonExtensionData] public global::System.Collections.Generic.Dictionary<string, object> ExtraFields { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();");
                    sb.AppendLine();
                }

                var properties = new List<(string LuaName, string CSharpName, string CSharpType, bool Optional)>();
                foreach (var prop in type.Properties!) {
                    var propInfo = GenerateProperty(sb, prop, hasParent, type.Name);
                    properties.Add(propInfo);
                }

                GenerateLuaBinding(sb, type.Name, properties, true);

                sb.AppendLine("    }");
                sb.AppendLine("}");

                context.AddSource($"Types.{type.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        private (string LuaName, string CSharpName, string CSharpType, bool Optional) GenerateProperty(StringBuilder sb,
            Property prop, bool hasParent, string className) {
            var csharpName = SnakeToPascal(prop.Name);

            if (csharpName == className) {
                csharpName += "Property";
            }

            bool isKeyword = Keywords.Contains(csharpName.ToLowerInvariant());
            bool isHiding = hasParent && (csharpName == "Name" || csharpName == "Type" || csharpName == "Order");

            string finalName = isKeyword ? "@" + csharpName : csharpName;
            string newKeyword = isHiding ? "new " : "";

            var csharpType = MapType(prop.Type);

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// {prop.Description.Replace("\n", "\n        /// ")}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [global::FactorioParanoidal.FactorioMods.Execution.SourceGenerator.LuaExtraMember]");
            sb.AppendLine($"        [JsonPropertyName(\"{prop.Name}\")]");

            string initializer = "";
            if (!prop.Optional) {
                initializer = " = default!;";
            }

            sb.AppendLine(
                $"        public {newKeyword}{csharpType}{(prop.Optional ? "?" : "")} {finalName} {{ get; set; }}{initializer}");
            sb.AppendLine();

            return (prop.Name, finalName, csharpType, prop.Optional);
        }

        private void GenerateLuaBinding(StringBuilder sb, string className,
            List<(string LuaName, string CSharpName, string CSharpType, bool Optional)> properties,
            bool hasExtraFields) {
            sb.AppendLine(
                $"        static readonly global::Lua.LuaFunction __metamethod_index_{className} = new global::Lua.LuaFunction(\"index\", (context, ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            var userData = context.GetArgument<global::FactorioParanoidal.FactorioMods.Execution.Prototypes.{className}>(0);");
            sb.AppendLine("            var key = context.GetArgument<global::System.String>(1);");
            sb.AppendLine("            switch (key)");
            sb.AppendLine("            {");

            foreach (var prop in properties) {
                sb.AppendLine($"                case \"{prop.LuaName}\":");
                sb.AppendLine(
                    $"                    return new global::System.Threading.Tasks.ValueTask<int>(context.Return(global::FactorioParanoidal.FactorioMods.Execution.Proxies.LuaValueUtility.ObjectToLuaValue(context.State, userData.{prop.CSharpName})));");
            }

            sb.AppendLine("                default:");
            if (hasExtraFields) {
                sb.AppendLine("                    if (userData.ExtraFields.TryGetValue(key, out var extraValue))");
                sb.AppendLine(
                    "                        return new global::System.Threading.Tasks.ValueTask<int>(context.Return(global::FactorioParanoidal.FactorioMods.Execution.Proxies.LuaValueUtility.ObjectToLuaValue(context.State, extraValue)));");
            }

            sb.AppendLine(
                "                    return new global::System.Threading.Tasks.ValueTask<int>(context.Return(global::Lua.LuaValue.Nil));");
            sb.AppendLine("            }");
            sb.AppendLine("        });");
            sb.AppendLine();

            sb.AppendLine(
                $"        static readonly global::Lua.LuaFunction __metamethod_newindex_{className} = new global::Lua.LuaFunction(\"newindex\", (context, ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            var userData = context.GetArgument<global::FactorioParanoidal.FactorioMods.Execution.Prototypes.{className}>(0);");
            sb.AppendLine("            var key = context.GetArgument<global::System.String>(1);");
            sb.AppendLine("            var value = context.GetArgument(2);");
            sb.AppendLine("            switch (key)");
            sb.AppendLine("            {");

            int i = 0;
            foreach (var prop in properties) {
                sb.AppendLine($"                case \"{prop.LuaName}\":");
                sb.AppendLine(
                    $"                    var propVal_{i} = global::FactorioParanoidal.FactorioMods.Execution.Proxies.LuaValueUtility.LuaValueToObject(value, typeof({prop.CSharpType}));");
                sb.AppendLine(
                    $"                    userData.{prop.CSharpName} = propVal_{i} == null ? default! : ({prop.CSharpType})propVal_{i};");
                sb.AppendLine("                    break;");
                i++;
            }

            sb.AppendLine("                default:");
            if (hasExtraFields) {
                sb.AppendLine("                    if (value == global::Lua.LuaValue.Nil)");
                sb.AppendLine("                        userData.ExtraFields.Remove(key);");
                sb.AppendLine("                    else");
                sb.AppendLine(
                    "                        userData.ExtraFields[key] = global::FactorioParanoidal.FactorioMods.Execution.Proxies.LuaValueUtility.LuaValueToObject(value, typeof(object))!;");
            }
            else {
                sb.AppendLine(
                    "                    throw new global::Lua.LuaRuntimeException(context.State, $\"'{key}' not found on {className}.\");");
            }

            sb.AppendLine("                    break;");
            sb.AppendLine("            }");
            sb.AppendLine("            return new global::System.Threading.Tasks.ValueTask<int>(context.Return());");
            sb.AppendLine("        });");
            sb.AppendLine();

            sb.AppendLine($"        static global::Lua.LuaTable? __metatable_{className};");
            sb.AppendLine($"        global::Lua.LuaTable? global::Lua.ILuaUserData.Metatable");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (__metatable_{className} != null) return __metatable_{className};");
            sb.AppendLine($"                __metatable_{className} = new global::Lua.LuaTable();");
            sb.AppendLine(
                $"                __metatable_{className}[global::Lua.Runtime.Metamethods.Index] = __metamethod_index_{className};");
            sb.AppendLine(
                $"                __metatable_{className}[global::Lua.Runtime.Metamethods.NewIndex] = __metamethod_newindex_{className};");
            sb.AppendLine($"                return __metatable_{className};");
            sb.AppendLine("            }");
            sb.AppendLine($"            set {{ __metatable_{className} = value; }}");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine(
                $"        public static implicit operator global::Lua.LuaValue(global::FactorioParanoidal.FactorioMods.Execution.Prototypes.{className} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            return global::Lua.LuaValue.FromUserData(value);");
            sb.AppendLine("        }");
        }

        private string MapType(JsonElement typeElement) {
            if (typeElement.ValueKind == JsonValueKind.String) {
                var typeStr = typeElement.GetString()!;
                if (TypeMapping.TryGetValue(typeStr, out var mapped)) return mapped;
                if (_generatedTypes.Contains(typeStr))
                    return "global::FactorioParanoidal.FactorioMods.Execution.Prototypes." + typeStr;

                if (_allTypeDefs.TryGetValue(typeStr, out var aliasTarget) &&
                    aliasTarget.ValueKind != JsonValueKind.Undefined) {
                    return MapType(aliasTarget);
                }

                return "object";
            }

            if (typeElement.ValueKind == JsonValueKind.Object) {
                var complex = JsonSerializer.Deserialize<ComplexType>(typeElement.GetRawText());
                if (complex == null) return "object";

                try {
                    switch (complex.Type) {
                        case "array":
                            return complex.Item.HasValue
                                ? $"global::System.Collections.Generic.List<{MapType(complex.Item.Value)}>"
                                : "global::System.Collections.Generic.List<object>";
                        case "dictionary":
                            return (complex.Key.HasValue && complex.Value.HasValue)
                                ? $"global::System.Collections.Generic.Dictionary<{MapType(complex.Key.Value)}, {MapType(complex.Value.Value)}>"
                                : "global::System.Collections.Generic.Dictionary<object, object>";
                        case "literal":
                            return complex.Value.HasValue ? GetJsonElementTypeName(complex.Value.Value) : "object";
                        case "type":
                            return complex.Value.HasValue ? MapType(complex.Value.Value) : "object";
                        case "union":
                        case "struct":
                        default:
                            return "object";
                    }
                }
                catch {
                    return "object";
                }
            }

            return "object";
        }

        private string GetJsonElementTypeName(JsonElement element) {
            switch (element.ValueKind) {
                case JsonValueKind.String: return "string";
                case JsonValueKind.Number: return "double";
                case JsonValueKind.True:
                case JsonValueKind.False: return "bool";
                default: return "object";
            }
        }

        private string SnakeToPascal(string snake) {
            if (string.IsNullOrEmpty(snake)) return snake;
            var words = snake.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
            for (int i = 0; i < words.Length; i++) {
                if (words[i].Length > 0) {
                    words[i] = char.ToUpper(words[i][0]) + words[i].Substring(1);
                }
            }

            return string.Join("", words);
        }
    }
}