using FluentAssertions;
using FactorioParanoidal.FactorioMods;

namespace FactorioParanoidal.FactorioMods.Tests;

public class ParanoidalModpackRealTest {
    [Fact]
    public async Task SortModsByLoadOrder_ShouldMatchFactorioLogOrder() {
        // Arrange
        var modpack = await FactorioModpack.LoadFromDirectory("Data/Paranoidal");

        // Act
        modpack.SortModsByLoadOrder();

        var actualOrder = modpack.Mods.Select(m => m.Info.Name).ToList();

        // Expected order from Factorio log (relative order of these specific mods)

        // Filter actual order to only include mods from the log
        var filteredActualOrder = actualOrder
            .Where(name => _expectedOrder.Contains(name))
            .ToList();

        // Assert
        filteredActualOrder.Should().BeEquivalentTo(_expectedOrder, options => options.WithStrictOrdering());
    }

    private readonly List<string> _expectedOrder = [
        "belt-visualizer",
        "EvoGUI",
        "minime_temp",
        "railloader",
        "rusty-locale",
        "what-is-it-really-used-for",
        "WireShortcuts",
        "AbandonedRuins",
        "AdditionalPasteSettings",
        "AlertsList2",
        "AtomicArtillery",
        "BatteryElectricTrain",
        "beautiful_straight_bridge_railway",
        "Big-Monsters",
        "BigLab",
        "bobinserters",
        "boblibrary",
        "bullet-trails",
        "comb",
        "CopyPasteModules",
        "DeadlockLargerLamp",
        "DeadlockResearchNotifications",
        "DeleteEmptyChunks",
        "DewPointAggregator",
        "efficient-research",
        "ElectricResistance",
        "Enhanced_Map_Colors",
        "even-distribution",
        "expanded-rocket-payloads",
        "FactorySearch",
        "FastRemoveTiles",
        "Fe-C-accumulator",
        "flib",
        "Flow Control",
        "FNEI",
        "ghost-counter",
        "helmod",
        "holographic_signs",
        "immersive-sounds",
        "inserter-throughput",
        "JunkTrain3",
        "Kruise_Kontrol_Updated",
        "laser_fix",
        "liborio",
        "LootingSpaceshipWrecks",
        "make_burner_miners_great_again",
        "mining-patch-planner",
        "MIRV",
        "more-minimap-autohide-017",
        "MoreAchievements",
        "MxlChievements",
        "m_WhereIsMyBody",
        "Namelists",
        "Nearby-Ammo-Count",
        "newtrainsfx",
        "NightBrightness",
        "Noxys_Trees",
        "OberNuclear",
        "Oil_Based_Paint",
        "osha_mini_containers",
        "osm-lib",
        "OverloadedTrains",
        "Picks-Inserter",
        "PMRPGsystem",
        "pollution-visuals",
        "qol_research",
        "QueueToFrontNG",
        "RadioactiveDamage",
        "RaiLuaLib",
        "RealisticDecorationCleanup",
        "RemoteConfiguration",
        "Renamer",
        "RITEG",
        "Robot256Lib",
        "robot_attrition",
        "RocketExplosions",
        "RussianStations",
        "scattergun_turret",
        "SchallPickupTower",
        "SchallTankPlatoon",
        "Shield-FX",
        "show-max-underground-distance",
        "SingleColorTerrain",
        "SpeedLimitSignsForTrains",
        "stdlib",
        "steinios_research_sensor",
        "Teleporters",
        "Texugo_windgenerator",
        "TimedSpawnControl",
        "Todo-List",
        "TrainModeSwitcher",
        "Train_Control_Signals",
        "underground-energy-distribution",
        "UnPollock",
        "VehicleSnap",
        "vehicle_physics_again",
        "Warehousing",
        "weaponSoundsRedone",
        "what-fish",
        "ZCS-Trash-Landfill-Continued-Continued",
        "zzzparanoidal-settings",
        "bobenemies",
        "bobequipment",
        "bobores",
        "BottleneckLite",
        "LogisticTrainNetwork",
        "Milestones",
        "ModuleInserter",
        "PickerAtheneum",
        "PickerTweaks",
        "PipeVisualizer",
        "QuickItemSearch",
        "RateCalculator",
        "upgrade-planner-next",
        "WideChests",
        "bobplates",
        "bobtech",
        "ltn-cleanup",
        "LtnManager",
        "LTN_Combinator_Fix",
        "LTN_Content_Reader",
        "Nanobots",
        "PickerBlueprinter",
        "PickerDollies",
        "PickerEquipmentKeys",
        "PickerExtended",
        "PickerInventoryTools",
        "PickerPipeTools",
        "PickerVehicles",
        "RampantFixed",
        "rso-mod",
        "Squeak Through",
        "bobassembly",
        "bobelectronics",
        "boblogistics",
        "bobmining",
        "bobpower",
        "bobrevamp",
        "bobwarfare",
        "deep-storage-unit",
        "FluidMustFlow",
        "BigLightElectricMiningDrill",
        "blueprint_flip_and_turn",
        "bobmodules",
        "BobPipesThroughput",
        "bobvehicleequipment",
        "Cursed-FMD",
        "fluid-memory-storage",
        "InfiniteTech",
        "miniloader",
        "RU-locale",
        "Subterranean",
        "toxicPollution",
        "Aircraft",
        "angelsrefining",
        "MilesBobsExpansion",
        "SpaceMod",
        "angelsinfiniteores",
        "angelspetrochem",
        "betterCargoPlanes",
        "Clowns-Nuclear",
        "CoppermineBobModuleRebalancing",
        "CW-carbon-capture-reforged",
        "GUI_Unifyer",
        "KS_Power",
        "research_evolution_factor",
        "SpaceXGAR",
        "angelssmelting",
        "Bio_Industries",
        "reskins-library",
        "ReStack",
        "aai-industry",
        "AbandonedRuins-Silly",
        "angels-smelting-extended",
        "angelsbioprocessing",
        "factorissimo-2-notnotmelon",
        "more-petrochem-hell",
        "reskins-bobs",
        "Rocket-Silo-Construction",
        "UnminableBots",
        "baraws",
        "blueprint-sandboxes",
        "Clowns-Processing",
        "Flammable_Oils_fix",
        "LightedPolesPlus",
        "marathon",
        "nco-InserterCranes",
        "Oberhaul",
        "OreRadar",
        "PCPRedux",
        "reskins-angels",
        "angelsextended-remelting-fixed",
        "Clowns-AngelBob-Nuclear",
        "extendedangels",
        "ShinyBob_Techs",
        "Shortcuts-ick",
        "ERPTbaAB",
        "KaoExtended",
        "reskins-compatibility",
        "bobicons",
        "multi-product-recipe-details",
        "ner_intermediatestweak",
        "prismatic-belts",
        "zzzparanoidal",
        "extended-descriptions",
        "fluid_permutations",
        "heroturrets",
        "osm-lib-postprocess",
        "ParanoidalLocale"
    ];
}