using System.Text;
using System.Text.Json;
using FactorioParanoidal.Generator.Prototypes.Models;

namespace FactorioParanoidal.Generator.Prototypes;

public class Program {
    private static readonly Dictionary<string, string> TypeMapping = new() {
        { "string", "string" },
        { "bool", "bool" },
        { "boolean", "bool" },
        { "double", "double" },
        { "float", "float" },
        { "int8", "sbyte" },
        { "uint8", "byte" },
        { "int16", "short" },
        { "uint16", "ushort" },
        { "int32", "int" },
        { "uint32", "uint" },
        { "int64", "long" },
        { "uint64", "ulong" },
        { "double_or_float", "double" },
        { "Energy", "string" },
        { "FileName", "string" },
        { "Order", "string" },
        { "Color", "object" },
        { "LocalisedString", "object" },
        { "Sound", "object" },
        { "Sprite", "object" },
        { "Animation", "object" },
        { "ItemID", "string" },
        { "EntityID", "string" },
        { "RecipeID", "string" },
        { "TechnologyID", "string" },
        { "TileID", "string" },
        { "FluidID", "string" },
        { "ItemSubGroupID", "string" },
        { "ItemGroupID", "string" },
        { "FuelCategoryID", "string" },
        { "EquipmentID", "string" },
        { "QualityID", "string" },
        { "SurfaceID", "string" },
        { "SpaceLocationID", "string" },
        { "VirtualSignalID", "string" },
    };

    private static readonly HashSet<string> Keywords = new() {
        "base", "class", "namespace", "object", "event", "delegate", "operator", "params", "checked", "unchecked",
        "default",
        "throw", "for", "foreach", "while", "do", "if", "else", "switch", "case", "break", "continue", "return",
        "using",
        "lock", "fixed", "new", "this", "true", "false", "null", "void", "static", "public", "private", "protected",
        "internal", "virtual", "override", "sealed", "abstract", "readonly", "volatile", "async", "await"
    };

    private static readonly HashSet<string> GeneratedTypes = new();
    private static readonly Dictionary<string, JsonElement> AllTypeDefs = new();

    public static async Task Main(string[] args) {
        var jsonPath = "prototype-api.json";
        if (!File.Exists(jsonPath)) {
            Console.WriteLine($"Error: {jsonPath} not found.");
            return;
        }

        var json = await File.ReadAllTextAsync(jsonPath);
        var api = JsonSerializer.Deserialize<PrototypeApi>(json);

        if (api == null) {
            Console.WriteLine("Error: Failed to deserialize JSON.");
            return;
        }

        var outputPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,
            "../../../../FactorioParanoidal.FactorioMods.Execution/Generated"));
        if (Directory.Exists(outputPath)) {
            Directory.Delete(outputPath, true);
        }

        Directory.CreateDirectory(outputPath);

        // Pre-collect all types and trace which ones will be classes
        foreach (var t in api.Types) AllTypeDefs[t.Name] = t.Type ?? default;

        foreach (var p in api.Prototypes) GeneratedTypes.Add(p.Name);
        foreach (var t in api.Types.Where(t => t.Properties != null && t.Properties.Count > 0))
            GeneratedTypes.Add(t.Name);

        GeneratePrototypes(api.Prototypes, outputPath);
        GenerateTypes(api.Types, outputPath);

        Console.WriteLine($"Generation completed. Files saved to: {outputPath}");
    }

    private static void GeneratePrototypes(List<Prototype> prototypes, string outputPath) {
        foreach (var prototype in prototypes) {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0108, CS0109");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using FactorioParanoidal.FactorioMods.Execution.SourceGenerator;");
            sb.AppendLine();
            sb.AppendLine("namespace FactorioParanoidal.FactorioMods.Execution.Prototypes;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {prototype.Description.Replace("\n", "\n/// ")}");
            sb.AppendLine("/// </summary>");

            if (!prototype.Abstract) {
                sb.AppendLine("[LuaExtraObject]");
            }

            string inheritance = "";
            if (prototype.Name != "PrototypeBase") {
                var parent = prototype.Parent ?? "PrototypeBase";
                if (parent == "FactorioPrototype" || parent == "Prototype") {
                    if (prototype.Name == "Prototype") parent = "PrototypeBase";
                    else parent = "PrototypeBase";
                }

                inheritance = $" : {parent}";
            }

            var abstractKeyword = prototype.Abstract ? "abstract " : "";
            sb.AppendLine($"public {abstractKeyword}partial class {prototype.Name}{inheritance}");
            sb.AppendLine("{");

            foreach (var prop in prototype.Properties) {
                GenerateProperty(sb, prop, prototype.Name != "PrototypeBase", prototype.Name);
            }

            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{prototype.Name}.g.cs"), sb.ToString());
        }
    }

    private static void GenerateTypes(List<TypeDefinition> types, string outputPath) {
        foreach (var type in types.Where(t => t.Properties != null && t.Properties.Count > 0)) {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0108, CS0109");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using FactorioParanoidal.FactorioMods.Execution.SourceGenerator;");
            sb.AppendLine();
            sb.AppendLine("namespace FactorioParanoidal.FactorioMods.Execution.Prototypes;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {type.Description.Replace("\n", "\n/// ")}");
            sb.AppendLine("/// </summary>");

            if (!type.Abstract) {
                sb.AppendLine("[LuaExtraObject]");
            }

            var parent = type.Parent;
            if (parent == "FactorioPrototype" || parent == "Prototype") parent = "PrototypeBase";
            var inheritance = !string.IsNullOrEmpty(parent) ? $" : {parent}" : "";

            var abstractKeyword = type.Abstract ? "abstract " : "";
            sb.AppendLine($"public {abstractKeyword}partial class {type.Name}{inheritance}");
            sb.AppendLine("{");

            foreach (var prop in type.Properties!) {
                GenerateProperty(sb, prop, !string.IsNullOrEmpty(parent), type.Name);
            }

            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputPath, $"{type.Name}.g.cs"), sb.ToString());
        }
    }

    private static void GenerateProperty(StringBuilder sb, Property prop, bool hasParent, string className) {
        var csharpName = SnakeToPascal(prop.Name);

        if (csharpName == className) {
            csharpName += "Property";
        }

        bool isKeyword = Keywords.Contains(csharpName.ToLowerInvariant());
        bool isHiding = hasParent && (csharpName == "Name" || csharpName == "Type" || csharpName == "Order");

        string finalName = isKeyword ? "@" + csharpName : csharpName;
        string newKeyword = isHiding ? "new " : "";

        var csharpType = MapType(prop.Type);

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// {prop.Description.Replace("\n", "\n    /// ")}");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [LuaExtraMember]");
        sb.AppendLine($"    [JsonPropertyName(\"{prop.Name}\")]");

        string initializer = "";
        if (!prop.Optional) {
            initializer = " = default!;";
        }

        sb.AppendLine(
            $"    public {newKeyword}{csharpType}{(prop.Optional ? "?" : "")} {finalName} {{ get; set; }}{initializer}");
        sb.AppendLine();
    }

    private static string MapType(JsonElement typeElement) {
        if (typeElement.ValueKind == JsonValueKind.String) {
            var typeStr = typeElement.GetString()!;
            if (TypeMapping.TryGetValue(typeStr, out var mapped)) return mapped;
            if (GeneratedTypes.Contains(typeStr)) return typeStr;

            // Handle Aliases
            if (AllTypeDefs.TryGetValue(typeStr, out var aliasTarget) &&
                aliasTarget.ValueKind != JsonValueKind.Undefined) {
                return MapType(aliasTarget);
            }

            return "object";
        }

        if (typeElement.ValueKind == JsonValueKind.Object) {
            var complex = JsonSerializer.Deserialize<ComplexType>(typeElement.GetRawText());
            if (complex == null) return "object";

            try {
                return complex.Type switch {
                    "array" => complex.Item.HasValue ? $"List<{MapType(complex.Item.Value)}>" : "List<object>",
                    "dictionary" => (complex.Key.HasValue && complex.Value.HasValue)
                        ? $"Dictionary<{MapType(complex.Key.Value)}, {MapType(complex.Value.Value)}>"
                        : "Dictionary<object, object>",
                    "literal" => complex.Value.HasValue ? GetJsonElementTypeName(complex.Value.Value) : "object",
                    "type" => complex.Value.HasValue ? MapType(complex.Value.Value) : "object",
                    "union" => "object",
                    "struct" => "object",
                    _ => "object"
                };
            }
            catch {
                return "object";
            }
        }

        return "object";
    }

    private static string GetJsonElementTypeName(JsonElement element) {
        return element.ValueKind switch {
            JsonValueKind.String => "string",
            JsonValueKind.Number => "double",
            JsonValueKind.True => "bool",
            JsonValueKind.False => "bool",
            _ => "object"
        };
    }

    private static string SnakeToPascal(string snake) {
        if (string.IsNullOrEmpty(snake)) return snake;
        var words = snake.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < words.Length; i++) {
            if (words[i].Length > 0) {
                words[i] = char.ToUpper(words[i][0]) + words[i].Substring(1);
            }
        }

        return string.Join("", words);
    }
}